
# ================= Bias Correction Configuration =================
# This configuration file is used for setting up the bias correction script.
# It contains paths, simulation settings, bias correction parameters, and options.

# Please note that this is a general guide. For more specific instructions, you should refer to the documentation provided by the developers or contact them directly.

# =============== Input for bias correction =========================
# File path -------------------------------------------------
bc_hist_path: "/g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r6i1p1f1/6hrLev" # path to the data for historical bias correction
bc_future_path: "/g/data/fs38/publications/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r6i1p1f1/6hrLev" # path to the data for future bias correction
obs_path: "/g/data/w28/yk8692/input/era5/access_esm" # observation data path
out_path: "/g/data/w28/yk8692/tests/access/calibration/tile_test_3d" # path to save the output

# Simulation periods, historical -----------------------------------
bc_hist: True # Yes: True, No: False
startyear_h: 1959 # start year for historical simulation
endyear_h: 1989 # end year for historical simulation

# GCM information
infor: "6hrLev" # 6hrLev for 3d, Oday for 2D
gname: "ACCESS-ESM1-5" # GCM name
period: "historical" # historical, validation, or future
cinfor: "r6i1p1f1"
sinfor: "gn"
version: "20200529"

# Simulation periods, future -----------------------------------
bc_future: True # Yes: True, No: False
startyear_f: 1990 # start year for future simulation
endyear_f: 2020 # end year for future simulation

# GCM information
scenario: "ssp370"
cinfor_f: "r6i1p1f1"
version_f: "20211213"
period_f: "validation" # historical, validation, or future

# Bias correction information -------------------------------------
bc_boundary: "lateral" # "surface" for 2D "lateral" for 3D
input_model: "reanalysis" # "reanalysis" for ERA5, "model" for CMIP6
target_variable: ["hus", "ta", "ua", "va"] # ["tos"] for 2D, ["hus", "ta", "ua", "va"] for 3D
slevel: 0 # start level for bias correction
elevel: 0 # end level for bias correction
no_of_variables: 3 # number of variables to be bias corrected, generally 3, 1 for 2D
no_of_iterations: 1 # number of iterations for bias correction, default: 1
correction_model: 4 # 1: mean, 2: mean and variance, 3: nested, 4: multivariate (default for 3D) : 1-3 should be used for 2D
sub_daily_correction: True # sub-daily bias correction, Yes: True, No: False

# Selected area ---------------------------------------------------
# latitudes and longitudes of the selected area
lat_min: 10 # -55
lat_max: 15 # -5
lon_min: 110 # 80
lon_max: 115 # 170

# Physical upper limit (wind speed (m/s), temperature (K), specific humidity (g/kg), sea surface temperature (K))
upper_limit: [190, 330, 100, 330]
lower_limit: [0.001, 137, 0.001, 270]
max_tile_size: 500 # maximum grid cells within each tile for bias correction depending on the memory of the machine

# Options for bias correction
save_bc_output: True # save the bias corrected output, if not, only the BC factors will be saved
cleanup_bc_inputs: True # remove bias-corrected intermediate files after reformatting

# Input file information for reformatting
archive_roots: ["/g/data/oi10/replicas/CMIP6", "/g/data/fs38/publications/CMIP6"]
var_to_table: {"hus":"6hrLev", "ta":"6hrLev", "ua":"6hrLev", "va":"6hrLev", "tos":"Oday", "ps":"Amon"}
# =============== Input for bias correction ended =========================
