schema_version: 2
workflow: interp_3d
experiment: era5_to_access_esm1_5_historical

paths:
  input_path: "/g/data/rt52/era5/pressure-levels/reanalysis"
  input_path_sst: "/g/data/rt52/era5/single-levels/reanalysis"
  input_z_path: "/g/data/rt52/era5/pressure-levels/reanalysis/z"
  output_path: "/g/data/w28/yk8692/input/era5/access_esm"

source:
  input_model: "reanalysis"

# Set the input_* fields below only for model-as-truth runs.
# Example:
# input_model: "gcm"
# input_infor: "6hrLev"
# input_gname: "CNRM-CM6-1"
# input_period: "historical"
# input_cinfor: "r1i1p1f2"
# input_sinfor: "gr"
# input_version: "v20180917"

target:
  target_model: "gcm"
  target_path: "/g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r6i1p1f1"
  target_path_sst: "/g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r6i1p1f1"
  target_g_path: null
  target_orog_path: "/g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r6i1p1f1"
  infor: "6hrLev"
  gname: "ACCESS-ESM1-5"
  period: "historical"
  cinfor: "r6i1p1f1"
  sinfor: "gn"
  version: "v20200529"

domain:
  lat_min: 10
  lat_max: 15
  lon_min: 110
  lon_max: 115

period:
  startyear_h: 1959
  endyear_h: 2014

resources:
  ncpus: 48
  mem_gb: 190
