schema_version: 2
workflow: interp_surface
experiment: era5_to_access_esm1_5_surface_ssp370

paths:
  input_path: "/g/data/rt52/era5/pressure-levels/reanalysis"
  input_path_sst: "/g/data/rt52/era5/single-levels/reanalysis"
  input_z_path: "/g/data/rt52/era5/pressure-levels/reanalysis/z"
  output_path: "/g/data/w28/yk8692/input/era5/access_esm"

source:
  input_model: "reanalysis"

target:
  target_model: "gcm"
  target_path: "/g/data/fs38/publications/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r6i1p1f1"
  target_path_sst: "/g/data/fs38/publications/CMIP6/ScenarioMIP/CSIRO/ACCESS-ESM1-5/ssp370/r6i1p1f1"
  target_g_path: null
  target_orog_path: "/g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r6i1p1f1"
  infor: "6hrLev"
  gname: "ACCESS-ESM1-5"
  period: "ssp370"
  cinfor: "r6i1p1f1"
  sinfor: "gn"
  version: "v20211213"

future:
  hist_target_path: "/g/data/fs38/publications/CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r6i1p1f1"

domain:
  lat_min: -90
  lat_max: 90
  lon_min: 0
  lon_max: 360

period:
  startyear_h: 2015
  endyear_h: 2020

resources:
  ncpus: 48
  mem_gb: 190
